[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.partitions = partition_custom.csv

lib_deps =
    lvgl/lvgl @ ^8.3.0
    bodmer/TFT_eSPI @ ^2.5.0
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson@^7.4.3

build_flags =
    ; Parametri per TFT_eSPI
    -D LV_FONT_MONTSERRAT_20=1
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=4
    -D TOUCH_CS=5
    -D SPI_FREQUENCY=40000000
    -D SPI_TOUCH_FREQUENCY=2500000
    ; Parametri per PubSubClient
    -D MQTT_MAX_PACKET_SIZE=1024
    ; Parametri per LVGL
    -D LV_CONF_SKIP
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE




